2025-10-20 15:34:25,942 - __main__ - ERROR - Invalid JSON in config file: Expecting ':' delimiter: line 18 column 11 (char 422)
Traceback (most recent call last):
  File "/home/emvekta/projects/interface-check/main_eye_scan.py", line 104, in load_config
    data = json.load(f)
  File "/home/emvekta/snap/code/211/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/json/__init__.py", line 293, in load
    return loads(fp.read(),
        cls=cls, object_hook=object_hook,
        parse_float=parse_float, parse_int=parse_int,
        parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/emvekta/snap/code/211/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/emvekta/snap/code/211/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/json/decoder.py", line 345, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emvekta/snap/code/211/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/json/decoder.py", line 361, in raw_decode
    obj, end = self.scan_once(s, idx)
               ~~~~~~~~~~~~~~^^^^^^^^
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 18 column 11 (char 422)
